# Usa una imagen oficial de Python como imagen base
FROM python:3.11-slim-bullseye

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Establece la variable de entorno para indicar que se está ejecutando en Docker
ENV DE_BUILD=docker

# Instala uv
RUN pip install uv

# Copia los archivos de gestión de dependencias
COPY pyproject.toml uv.lock ./

# Instala las dependencias usando uv
RUN uv sync

# Copia el código de la aplicación y los recursos necesarios
COPY src/api ./src/api
COPY models ./models
COPY configs ./configs

# Expone el puerto en el que se ejecutará la aplicación
EXPOSE 8000

# Comando para ejecutar la aplicación
CMD ["uv", "run", "uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
