model:
  best_model: HistGradientBoostingClassifier
  f1: 0.08584474885844749
  list_categorical_features:
  - FLAG_OWN_CAR
  - FLAG_OWN_REALTY
  - NAME_INCOME_TYPE
  - NAME_EDUCATION_TYPE
  - NAME_FAMILY_STATUS
  - NAME_HOUSING_TYPE
  - OCCUPATION_TYPE
  - FLAG_WORK_PHONE
  - FLAG_PHONE
  - FLAG_EMAIL
  list_numeric_features:
  - AGE
  - CNT_CHILDREN
  - AMT_INCOME_TOTAL
  - WORK_YEARS
  name: good_bad_applicant_model
  parameters:
    learning_rate: 0.05
    max_iter: 200
    max_leaf_nodes: 31
    min_samples_leaf: 10
    random_state: 5000
  recall: 0.752
  target_variable: STATUS
